"""user phone number set unique

Revision ID: 21ebf5ea30a2
Revises: cbe12696b69b
Create Date: 2024-01-16 17:37:42.713165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ebf5ea30a2'
down_revision: Union[str, None] = 'cbe12696b69b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_user_phone_number', table_name='test_user')
    op.create_index(op.f('ix_test_user_phone_number'), 'test_user', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_user_phone_number'), table_name='test_user')
    op.create_index('ix_test_user_phone_number', 'test_user', ['phone_number'], unique=False)
    # ### end Alembic commands ###
